name: Run Tests
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.14"
      - name: Install dependencies
        run: |
          pipx install uv==0.10.8 && uv run make html
      - name: Run test suite
        run: |
          PYTHONPATH=`pwd` uv run pytest